### ISSUE TITLE
Exception: read 52.192.50.157:443 timeout after 30 seconds in 

### ISSUE THREAD

**Issue by phpmac** [workman-layout/Workman#81]
```
[2024-04-20 17:01:26] local.INFO: Exception: read 52.192.50.157:443 timeout after 30 seconds in /var/www/html/vendor/workerman/http-client/src/Request.php:461
Stack trace:
#0 [internal function]: Workerman\Http\Request->onError()
#1 /var/www/html/vendor/workerman/http-client/src/ConnectionPool.php(187): call_user_func()
#2 /var/www/html/vendor/workerman/workerman/Events/Select.php(238): Workerman\Http\ConnectionPool->closeTimeoutConnection()
#3 /var/www/html/vendor/workerman/workerman/Events/Select.php(299): Workerman\Events\Select->tick()
#4 /var/www/html/vendor/workerman/workerman/Worker.php(1638): Workerman\Events\Select->loop()
#5 /var/www/html/vendor/workerman/workerman/Worker.php(1429): Workerman\Worker::forkOneWorkerForLinux()
#6 /var/www/html/vendor/workerman/workerman/Worker.php(1403): Workerman\Worker::forkWorkersForLinux()
#7 /var/www/html/vendor/workerman/workerman/Worker.php(1788): Workerman\Worker::forkWorkers()
#8 /var/www/html/vendor/workerman/workerman/Worker.php(1724): Workerman\Worker::monitorWorkersForLinux()
#9 /var/www/html/vendor/workerman/workerman/Worker.php(562): Workerman\Worker::monitorWorkers()
#10 /var/www/html/public/binance/swap/swap_kline_4hour.php(243): Workerman\Worker::runAll()
#11 {main}  

```

如何处理这种异常？在哪里可以补货处理

**Comment by joel0** [comment]
Hi @phpmac .  It looks like you're on the wrong GitHub repository.  You seem to be using [Workerman](https://github.com/walkor/workerman).

看起来您位于错误的存储库上。 您似乎正在使用 [Workerman](https://github.com/walkor/workerman)。
